config/routes.rb
Rails.application.routes.draw do
  resources :recipes

  root to: "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients
  has_many :directions
  belongs_to :ingredients
  belongs_to :directions

  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true
  validates :title, :description, :image, presence: true
  has_attached_file :image, styles: { :medium => "400x400#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/solution/lib/card.rb
class Card
  RANKS = [:A, 2, 3, 4, 5, 6, 7, 8, 9, 10, :J, :Q, :K]
  SUITS = [:clubs, :diamonds, :hearts, :spades]

  attr_reader :rank, :suit

  def initialize(rank, suit)
    @rank = rank
    @suit = suit
  end

  def greater_than?(other)
    RANKS.index(self.rank) > RANKS.index(other.rank)
  end

  def ==(other)
    self.rank == other.rank && self.suit == other.suit
  end
end

app/models/solution/lib/deck.rb
require_relative "card"

class Deck
  def initialize
    @cards = []
    Card::SUITS.each do |suit|
      Card::RANKS.each do |rank|
        @cards.push(Card.new(rank, suit))
      end
    end
  end

  def cards_left
    @cards.length
  end

  def draw
    @cards.shift
  end

  def shuffle
    @cards.shuffle!
  end
end

app/models/step.rb
class Step < ApplicationRecord #ActiveRecord::Base
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipe = Recipe.all.order("created_at DESC")
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: "Successfully created new recipe"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path, notice: "Successfully deleted recipe"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Recipe App
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags

%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Recipe Box", root_path

      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Recipe", new_recipe_path
        %li= link_to "Sign Out", root_path

    .container
      -flash.each do |name, msg|
        = content_tag :div, msg, class: "alert"

      = yield

app/views/recipes/_direction_fields.html.haml
-# .form-inline.clearfix
-#   .nested-fields
-#     = f.input :step, input_html: {class: "form-input form-control"}
-#     = link_to_remove_association "Remove", f, class: "btn btn-default form-button"

app/views/recipes/_form.html.haml
= simple_form_for @recipe, html: { multipart: true } do |f|
  - if @recipe.errors.any?
    #errors
      %p
        = @recipe.errors.count
        Prevented this recipe from saving

      %ul
        - @recipe.errors.full_messages.each do |msg|
          %li= msg
  .panel-body
    = f.input :title, input_html: { class: 'form-control' }
    = f.input :description, input_html: { class: 'form-control' }
    = f.input :image, input_html: { class: 'form-control' }

    .row
      .col-md-6
        %h3 ingredients
        #ingredients
          = f.simple_fields_for :ingredients do |ingredient|
            = render 'ingredient_fields',f: ingredient
          .links
            = link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button"

    .row
      .col-md-6
        %h3 Directions
        #directions
          = f.simple_fields_for :directions do |direction|
            = render 'direction_fields', f: direction
          .links
            = link_to_add_association "Add Step", f, :directions, class: "btn btn-default add-button"

  = f.button :submit, class: "btn btn-primary"

app/views/recipes/_ingredient_fields.html.haml
-# .form-inline.clearfix
-#   .nested-fields
-#     = f.input :ingredient, input_html: {class: "form-input form-control"}
-#     = link_to_remove_association "Remove", f, class: "form-button btn btn-default"

app/views/recipes/edit.html.haml
%h1 Edit Recipe

= render 'form'

app/views/recipes/index.html.haml
- @recipe.each_slice(3) do |recipes|
  .row
    - recipes.each do |recipe|
      .col-md-4
        .recipe
          .image_wrapper
            = link_to recipe do
              = image_tag recipe.image.url(:medium)
          %h2= link_to recipe.title, recipe

app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'

%br/

=link_to "Back", root_path, class: "btn btn-default"

app/views/recipes/show.html.haml
= image_tag @recipe.image.url(:medium, class: "recipe_image")
%h1= @recipe.title
%p= @recipe.description

= link_to "Back", root_path, class: "btn btn-default"
= link_to "Edit", edit_recipe_path, class: "btn btn-default"
= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default"